from .Card import Card
from .All import *
from .Beast import *
from .Demon import *
from .Dragon import *
from .Elemental import *
from .Mech import *
from .Murloc import *
from .Neutral import *
from .Pirate import *
from .Quilboar import *
